- name: install and run nginx
  hosts: web
  tasks:
    - name: install nginx package
      ansible.builtin.playbook:
        name: nginx
        state: present
    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started 
