- name: install and run nginx 
  hosts: web # whitch host
  become: yes #for root 
  tasks:
  - name: install nginx package #task1
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx # task 2
    ansible.builtin.service:
      name: nginx
      state: started 
