- name: play-1
  hosts: web
  vars:
    course: "Devops"
    Trainer: "Susmitha"
    Duration: "12HRS"
  tasks:
  - name: check variable
    ansible.builtin.debug:
      msg: "Hi, i am learning {{course}}, Trainer is {{Trainer}}, duration is {{Duration}}"  

