- name: checking data types
  hosts: localhost
  vars:
    NAME: Shiva #key value
    Skils:  # skils is list type
    - Devops
    - Shell
    - Ansible
    Experience: #map type
      Devops: 5
      AWS: 3
      DOCKER: 2
    Trainer: true # boolen
  tasks:
  - name: print key value pair
    ansible.builtin.debug:
      msg: "name: {{NAME}}"

  - name: print list
    ansible.builtin.debug:
      msg: "Skils: {{skils}}"

  - name: print map
    ansible.builtin.debug:
      msg: "Experience: {{Experience}}"

  - name: print boolen
    ansible.builtin.debug:
      msg: "is he trainer: {{Trainer}}"              




