- name: checking data types
  hosts: localhost
  vars:
    NAME: Susmitha #key value pair
    Skils:  #skil is list type
    - Devops
    - AWS
    - Shell
    Experience: # this map type contain key value
      Devops: 5
      Shell: 3
      AWS: 1
    Trainer: True
  tasks: 
  - name: print key value pair
    ansible.builtin.debug:
      msg: "name: {{NAME}}"

  - name: print list
    ansible.builtin.debug:
      msg: "Skils: {{Skils}}"

  - name: print map
    ansible.builtin.debug:
      msg: "Experience: {{Experience}}"

  - name: print boolen
    ansible.builtin.debug:
      msg: "is he Trainer: {{Trainer}}"     

             




