- name: conditions
  hosts: localhost
  tasks:
  - name: check roboshop user id exist or not
    ansible.builtin.command: id roboshop
    register: user  #variable name
    ignore_errors: true

  - name: print variable value
    ansible.builtin.debug:
      msg: "user output is: {{user}}"

  - name: print exit ststus or return code
    ansible.builtin.debug:
      msg: "status is: {{user.rc}}"