- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check roboshop user id exist or not
    ansible.builtin.command: id roboshop
    register: user  #variable name
    ignore_errors: true

  - name: print variable value
    ansible.builtin.debug:
      msg: "user output is: {{user}}"

  - name: print exit ststus or return code
    ansible.builtin.debug:
      msg: "status is: {{user.rc}}"

  - name: create user
    ansible.builtin.user:
      name= roboshop
    when: user.rc !=0 #condition   