- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print package
    ansible.builtin.package:
      name: "{{item}}"
      state: present 
    loop: # to refer all memors, user iteam(default key) in ansible
    - git
    - mysql
     
    
