- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install or uninstall packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}" 
    loop: # to refer all memors, user iteam(default key) in ansible
    - {name: 'git', state: 'present'}
    - {name: 'mysql', state: 'absent'}
    - {name: 'nginx', state: 'present'}
     