- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install or uninstall package
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}" 
    loop: # to refer all memors, user iteam(default key) in ansible
    - {name: 'git', staste: 'present'}
    - {name: 'mysql', staste: 'obsent'}
    - {name: 'nginx', staste: 'present'}
     